spring:
  datasource:
    url: jdbc:mysql://43.226.43.165:3306/mysql180608321f_db?characterEncoding=utf8
    username: mysql180608321f
    password: 321f50X1ae
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*.xml
